// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: badgeRecievers.sql

package database

import (
	"context"
)

const createBadgeReceiver = `-- name: CreateBadgeReceiver :exec
INSERT INTO badge_receivers(telegram_id, has_test_badge, created_at, updated_at)
VALUES($1, $2, NOW()::TIMESTAMP, NOW()::TIMESTAMP)
`

type CreateBadgeReceiverParams struct {
	TelegramID   int64
	HasTestBadge bool
}

func (q *Queries) CreateBadgeReceiver(ctx context.Context, arg CreateBadgeReceiverParams) error {
	_, err := q.db.Exec(ctx, createBadgeReceiver, arg.TelegramID, arg.HasTestBadge)
	return err
}
