// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: badgeRecievers.sql

package database

import (
	"context"
)

const createBadgeReceiver = `-- name: CreateBadgeReceiver :exec
INSERT INTO badge_receivers(telegram_id, has_test_badge, created_at, updated_at)
VALUES($1, $2, NOW()::TIMESTAMP, NOW()::TIMESTAMP)
`

type CreateBadgeReceiverParams struct {
	TelegramID   int64
	HasTestBadge bool
}

func (q *Queries) CreateBadgeReceiver(ctx context.Context, arg CreateBadgeReceiverParams) error {
	_, err := q.db.Exec(ctx, createBadgeReceiver, arg.TelegramID, arg.HasTestBadge)
	return err
}

const sendFeedbackBadge = `-- name: SendFeedbackBadge :exec
UPDATE badge_receivers SET has_feedback_badge = TRUE
WHERE telegram_id = $1
`

func (q *Queries) SendFeedbackBadge(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, sendFeedbackBadge, telegramID)
	return err
}

const sendTestBage = `-- name: SendTestBage :exec
UPDATE badge_receivers SET has_test_badge = TRUE
WHERE telegram_id = $1
`

func (q *Queries) SendTestBage(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, sendTestBage, telegramID)
	return err
}
