// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForInsertBetaTesters implements pgx.CopyFromSource.
type iteratorForInsertBetaTesters struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBetaTesters) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBetaTesters) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForInsertBetaTesters) Err() error {
	return nil
}

func (q *Queries) InsertBetaTesters(ctx context.Context, telegramUsername []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"private_beta_testers"}, []string{"telegram_username"}, &iteratorForInsertBetaTesters{rows: telegramUsername})
}
