// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Position struct {
	Trader           int64
	TokenAddress     string
	TotalMonCost     pgtype.Numeric
	TotalTokenAmount pgtype.Numeric
	IsHidden         bool
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type PrivateBetaTester struct {
	TelegramUsername     string
	SentBadgeMsg         pgtype.Bool
	SentFeedbackBadgeMsg pgtype.Bool
	GaveFeedback         pgtype.Bool
}

type Setting struct {
	TelegramID      int64
	BuySlippage     int16
	SellSlippage    int16
	MaxPriceImpact  int16
	PriorityFee     string
	AutoBuy         bool
	AutoBuyAmount   pgtype.Numeric
	BuyButtonLeft   pgtype.Numeric
	BuyButtonRight  pgtype.Numeric
	SellButtonLeft  int16
	SellButtonRight int16
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type Transaction struct {
	Trader             pgtype.Int8
	WalletAddress      string
	FromToken          string
	ToToken            string
	FromAmount         pgtype.Numeric
	ToAmount           pgtype.Numeric
	TxHash             string
	TradeUnixTimestamp pgtype.Timestamp
	WebhookEventID     pgtype.Text
	CreatedAt          pgtype.Timestamp
}

type User struct {
	TelegramID         int64
	ChatID             int64
	WalletAddress      string
	ReferrerID         pgtype.Int8
	ReferralCode       string
	ReferrerFeePercent int16
	ReferralEarnings   pgtype.Numeric
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}
