// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	TelegramID    int64
	WalletAddress string
	ReferrerID    sql.NullInt64
	ReferralCode  string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
