// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: positions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const callGetPositionFunc = `-- name: CallGetPositionFunc :one
SELECT trader, token_address, total_mon_cost, total_token_amount, CAST(total_mon_cost / total_token_amount AS NUMERIC) AS average_mon_price FROM getPosition($1, $2)
`

type CallGetPositionFuncParams struct {
	Traderid     int64
	Tokenaddress string
}

type CallGetPositionFuncRow struct {
	Trader           int64
	TokenAddress     string
	TotalMonCost     pgtype.Numeric
	TotalTokenAmount pgtype.Numeric
	AverageMonPrice  pgtype.Numeric
}

func (q *Queries) CallGetPositionFunc(ctx context.Context, arg CallGetPositionFuncParams) (CallGetPositionFuncRow, error) {
	row := q.db.QueryRow(ctx, callGetPositionFunc, arg.Traderid, arg.Tokenaddress)
	var i CallGetPositionFuncRow
	err := row.Scan(
		&i.Trader,
		&i.TokenAddress,
		&i.TotalMonCost,
		&i.TotalTokenAmount,
		&i.AverageMonPrice,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :exec
INSERT INTO positions (trader, token_address, total_mon_cost, total_token_amount, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePositionParams struct {
	Trader           int64
	TokenAddress     string
	TotalMonCost     pgtype.Numeric
	TotalTokenAmount pgtype.Numeric
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) error {
	_, err := q.db.Exec(ctx, createPosition,
		arg.Trader,
		arg.TokenAddress,
		arg.TotalMonCost,
		arg.TotalTokenAmount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions WHERE trader = $1 AND token_address = $2
`

type DeletePositionParams struct {
	Trader       int64
	TokenAddress string
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) error {
	_, err := q.db.Exec(ctx, deletePosition, arg.Trader, arg.TokenAddress)
	return err
}

const deleteUserPositions = `-- name: DeleteUserPositions :exec
DELETE FROM positions WHERE trader = $1
`

func (q *Queries) DeleteUserPositions(ctx context.Context, trader int64) error {
	_, err := q.db.Exec(ctx, deleteUserPositions, trader)
	return err
}

const getHiddenPositions = `-- name: GetHiddenPositions :many
SELECT token_address FROM positions
WHERE trader = $1 AND is_hidden = TRUE
`

func (q *Queries) GetHiddenPositions(ctx context.Context, trader int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getHiddenPositions, trader)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token_address string
		if err := rows.Scan(&token_address); err != nil {
			return nil, err
		}
		items = append(items, token_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPosition = `-- name: GetPosition :one
SELECT is_hidden, total_mon_cost, total_token_amount, CAST(total_mon_cost / total_token_amount AS NUMERIC) AS average_mon_price FROM positions
WHERE trader = $1 AND token_address = $2
`

type GetPositionParams struct {
	Trader       int64
	TokenAddress string
}

type GetPositionRow struct {
	IsHidden         bool
	TotalMonCost     pgtype.Numeric
	TotalTokenAmount pgtype.Numeric
	AverageMonPrice  pgtype.Numeric
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (GetPositionRow, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.Trader, arg.TokenAddress)
	var i GetPositionRow
	err := row.Scan(
		&i.IsHidden,
		&i.TotalMonCost,
		&i.TotalTokenAmount,
		&i.AverageMonPrice,
	)
	return i, err
}

const getUserPositions = `-- name: GetUserPositions :many
SELECT token_address, total_mon_cost, CAST(total_mon_cost / total_token_amount AS NUMERIC) AS average_mon_price FROM positions
WHERE trader = $1 AND is_hidden = FALSE
`

type GetUserPositionsRow struct {
	TokenAddress    string
	TotalMonCost    pgtype.Numeric
	AverageMonPrice pgtype.Numeric
}

func (q *Queries) GetUserPositions(ctx context.Context, trader int64) ([]GetUserPositionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPositions, trader)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPositionsRow
	for rows.Next() {
		var i GetUserPositionsRow
		if err := rows.Scan(&i.TokenAddress, &i.TotalMonCost, &i.AverageMonPrice); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hidePosition = `-- name: HidePosition :exec
SELECT hidePosition(traderId => $1, tokenAddress => $2)
`

type HidePositionParams struct {
	Traderid     int64
	Tokenaddress string
}

func (q *Queries) HidePosition(ctx context.Context, arg HidePositionParams) error {
	_, err := q.db.Exec(ctx, hidePosition, arg.Traderid, arg.Tokenaddress)
	return err
}

const mutatePosition = `-- name: MutatePosition :exec
SELECT mutatePosition(traderId => $1, tokenAddress => $2, mon_cost => $3, token_amount => $4)
`

type MutatePositionParams struct {
	Traderid     int64
	Tokenaddress string
	MonCost      pgtype.Numeric
	TokenAmount  pgtype.Numeric
}

func (q *Queries) MutatePosition(ctx context.Context, arg MutatePositionParams) error {
	_, err := q.db.Exec(ctx, mutatePosition,
		arg.Traderid,
		arg.Tokenaddress,
		arg.MonCost,
		arg.TokenAmount,
	)
	return err
}

const mutatePositionSell = `-- name: MutatePositionSell :exec
SELECT mutatePositionSell(traderId => $1, tokenAddress => $2, token_amount => $3)
`

type MutatePositionSellParams struct {
	Traderid     int64
	Tokenaddress string
	TokenAmount  pgtype.Numeric
}

func (q *Queries) MutatePositionSell(ctx context.Context, arg MutatePositionSellParams) error {
	_, err := q.db.Exec(ctx, mutatePositionSell, arg.Traderid, arg.Tokenaddress, arg.TokenAmount)
	return err
}

const unhidePosition = `-- name: UnhidePosition :exec
SELECT unhidePosition(traderId => $1, tokenAddress => $2)
`

type UnhidePositionParams struct {
	Traderid     int64
	Tokenaddress string
}

func (q *Queries) UnhidePosition(ctx context.Context, arg UnhidePositionParams) error {
	_, err := q.db.Exec(ctx, unhidePosition, arg.Traderid, arg.Tokenaddress)
	return err
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE positions SET total_mon_cost = $3, total_token_amount = $4, updated_at = $5
WHERE trader = $1 AND token_address = $2
`

type UpdatePositionParams struct {
	Trader           int64
	TokenAddress     string
	TotalMonCost     pgtype.Numeric
	TotalTokenAmount pgtype.Numeric
	UpdatedAt        pgtype.Timestamp
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.Exec(ctx, updatePosition,
		arg.Trader,
		arg.TokenAddress,
		arg.TotalMonCost,
		arg.TotalTokenAmount,
		arg.UpdatedAt,
	)
	return err
}
