// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: privateBetaTesters.sql

package database

import (
	"context"
)

const isBetaTester = `-- name: IsBetaTester :one
SELECT EXISTS (SELECT 1 FROM private_beta_testers WHERE telegram_username = $1)
`

func (q *Queries) IsBetaTester(ctx context.Context, telegramUsername string) (bool, error) {
	row := q.db.QueryRow(ctx, isBetaTester, telegramUsername)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const privateBetaTestersExists = `-- name: PrivateBetaTestersExists :one
SELECT EXISTS (SELECT 1 FROM private_beta_testers WHERE telegram_username IS NOT NULL LIMIT 1)
`

func (q *Queries) PrivateBetaTestersExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, privateBetaTestersExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
