// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSettings = `-- name: CreateUserSettings :exec
INSERT INTO settings(telegram_id, buy_slippage, sell_slippage, max_price_impact, priority_fee, auto_buy, auto_buy_amount, buy_button_left, buy_button_right, sell_button_left, sell_button_right, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateUserSettingsParams struct {
	TelegramID      int64
	BuySlippage     int16
	SellSlippage    int16
	MaxPriceImpact  int16
	PriorityFee     string
	AutoBuy         bool
	AutoBuyAmount   pgtype.Numeric
	BuyButtonLeft   pgtype.Numeric
	BuyButtonRight  pgtype.Numeric
	SellButtonLeft  int16
	SellButtonRight int16
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

func (q *Queries) CreateUserSettings(ctx context.Context, arg CreateUserSettingsParams) error {
	_, err := q.db.Exec(ctx, createUserSettings,
		arg.TelegramID,
		arg.BuySlippage,
		arg.SellSlippage,
		arg.MaxPriceImpact,
		arg.PriorityFee,
		arg.AutoBuy,
		arg.AutoBuyAmount,
		arg.BuyButtonLeft,
		arg.BuyButtonRight,
		arg.SellButtonLeft,
		arg.SellButtonRight,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getBuySellButtons = `-- name: GetBuySellButtons :one
SELECT buy_button_left, buy_button_right, sell_button_left, sell_button_right FROM settings
WHERE telegram_id = $1
`

type GetBuySellButtonsRow struct {
	BuyButtonLeft   pgtype.Numeric
	BuyButtonRight  pgtype.Numeric
	SellButtonLeft  int16
	SellButtonRight int16
}

func (q *Queries) GetBuySellButtons(ctx context.Context, telegramID int64) (GetBuySellButtonsRow, error) {
	row := q.db.QueryRow(ctx, getBuySellButtons, telegramID)
	var i GetBuySellButtonsRow
	err := row.Scan(
		&i.BuyButtonLeft,
		&i.BuyButtonRight,
		&i.SellButtonLeft,
		&i.SellButtonRight,
	)
	return i, err
}

const getTradeData = `-- name: GetTradeData :one
SELECT buySlippage, sellSlippage, maxPriceImpact, referrerFeePercent, referrerAddress, priorityFee FROM getTradeData($1)
`

type GetTradeDataRow struct {
	Buyslippage        pgtype.Int2
	Sellslippage       pgtype.Int2
	Maxpriceimpact     pgtype.Int2
	Referrerfeepercent pgtype.Int2
	Referreraddress    interface{}
	Priorityfee        interface{}
}

func (q *Queries) GetTradeData(ctx context.Context, telegramid int64) (GetTradeDataRow, error) {
	row := q.db.QueryRow(ctx, getTradeData, telegramid)
	var i GetTradeDataRow
	err := row.Scan(
		&i.Buyslippage,
		&i.Sellslippage,
		&i.Maxpriceimpact,
		&i.Referrerfeepercent,
		&i.Referreraddress,
		&i.Priorityfee,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT telegram_id, buy_slippage, sell_slippage, max_price_impact, priority_fee, auto_buy, auto_buy_amount, buy_button_left, buy_button_right, sell_button_left, sell_button_right, created_at, updated_at FROM settings
WHERE telegram_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, telegramID int64) (Setting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, telegramID)
	var i Setting
	err := row.Scan(
		&i.TelegramID,
		&i.BuySlippage,
		&i.SellSlippage,
		&i.MaxPriceImpact,
		&i.PriorityFee,
		&i.AutoBuy,
		&i.AutoBuyAmount,
		&i.BuyButtonLeft,
		&i.BuyButtonRight,
		&i.SellButtonLeft,
		&i.SellButtonRight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersSettings = `-- name: GetUsersSettings :many
SELECT telegram_id, buy_slippage, sell_slippage, max_price_impact, priority_fee, auto_buy, auto_buy_amount, buy_button_left, buy_button_right, sell_button_left, sell_button_right, created_at, updated_at FROM settings
`

func (q *Queries) GetUsersSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, getUsersSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.TelegramID,
			&i.BuySlippage,
			&i.SellSlippage,
			&i.MaxPriceImpact,
			&i.PriorityFee,
			&i.AutoBuy,
			&i.AutoBuyAmount,
			&i.BuyButtonLeft,
			&i.BuyButtonRight,
			&i.SellButtonLeft,
			&i.SellButtonRight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutoBuy = `-- name: UpdateAutoBuy :exec
UPDATE settings SET auto_buy = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateAutoBuyParams struct {
	TelegramID int64
	AutoBuy    bool
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) UpdateAutoBuy(ctx context.Context, arg UpdateAutoBuyParams) error {
	_, err := q.db.Exec(ctx, updateAutoBuy, arg.TelegramID, arg.AutoBuy, arg.UpdatedAt)
	return err
}

const updateAutoBuyAmount = `-- name: UpdateAutoBuyAmount :exec
UPDATE settings SET auto_buy_amount = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateAutoBuyAmountParams struct {
	TelegramID    int64
	AutoBuyAmount pgtype.Numeric
	UpdatedAt     pgtype.Timestamp
}

func (q *Queries) UpdateAutoBuyAmount(ctx context.Context, arg UpdateAutoBuyAmountParams) error {
	_, err := q.db.Exec(ctx, updateAutoBuyAmount, arg.TelegramID, arg.AutoBuyAmount, arg.UpdatedAt)
	return err
}

const updateBuyButtonLeft = `-- name: UpdateBuyButtonLeft :exec
UPDATE settings SET buy_button_left = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateBuyButtonLeftParams struct {
	TelegramID    int64
	BuyButtonLeft pgtype.Numeric
	UpdatedAt     pgtype.Timestamp
}

func (q *Queries) UpdateBuyButtonLeft(ctx context.Context, arg UpdateBuyButtonLeftParams) error {
	_, err := q.db.Exec(ctx, updateBuyButtonLeft, arg.TelegramID, arg.BuyButtonLeft, arg.UpdatedAt)
	return err
}

const updateBuyButtonRight = `-- name: UpdateBuyButtonRight :exec
UPDATE settings SET buy_button_right = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateBuyButtonRightParams struct {
	TelegramID     int64
	BuyButtonRight pgtype.Numeric
	UpdatedAt      pgtype.Timestamp
}

func (q *Queries) UpdateBuyButtonRight(ctx context.Context, arg UpdateBuyButtonRightParams) error {
	_, err := q.db.Exec(ctx, updateBuyButtonRight, arg.TelegramID, arg.BuyButtonRight, arg.UpdatedAt)
	return err
}

const updateBuySlippage = `-- name: UpdateBuySlippage :exec
UPDATE settings SET buy_slippage = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateBuySlippageParams struct {
	TelegramID  int64
	BuySlippage int16
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) UpdateBuySlippage(ctx context.Context, arg UpdateBuySlippageParams) error {
	_, err := q.db.Exec(ctx, updateBuySlippage, arg.TelegramID, arg.BuySlippage, arg.UpdatedAt)
	return err
}

const updateMaxPriceImpact = `-- name: UpdateMaxPriceImpact :exec
UPDATE settings SET max_price_impact = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateMaxPriceImpactParams struct {
	TelegramID     int64
	MaxPriceImpact int16
	UpdatedAt      pgtype.Timestamp
}

func (q *Queries) UpdateMaxPriceImpact(ctx context.Context, arg UpdateMaxPriceImpactParams) error {
	_, err := q.db.Exec(ctx, updateMaxPriceImpact, arg.TelegramID, arg.MaxPriceImpact, arg.UpdatedAt)
	return err
}

const updatePriorityFee = `-- name: UpdatePriorityFee :exec
UPDATE settings SET priority_fee = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdatePriorityFeeParams struct {
	TelegramID  int64
	PriorityFee string
	UpdatedAt   pgtype.Timestamp
}

func (q *Queries) UpdatePriorityFee(ctx context.Context, arg UpdatePriorityFeeParams) error {
	_, err := q.db.Exec(ctx, updatePriorityFee, arg.TelegramID, arg.PriorityFee, arg.UpdatedAt)
	return err
}

const updateSellButtonLeft = `-- name: UpdateSellButtonLeft :exec
UPDATE settings SET sell_button_left = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateSellButtonLeftParams struct {
	TelegramID     int64
	SellButtonLeft int16
	UpdatedAt      pgtype.Timestamp
}

func (q *Queries) UpdateSellButtonLeft(ctx context.Context, arg UpdateSellButtonLeftParams) error {
	_, err := q.db.Exec(ctx, updateSellButtonLeft, arg.TelegramID, arg.SellButtonLeft, arg.UpdatedAt)
	return err
}

const updateSellButtonRight = `-- name: UpdateSellButtonRight :exec
UPDATE settings SET sell_button_right = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateSellButtonRightParams struct {
	TelegramID      int64
	SellButtonRight int16
	UpdatedAt       pgtype.Timestamp
}

func (q *Queries) UpdateSellButtonRight(ctx context.Context, arg UpdateSellButtonRightParams) error {
	_, err := q.db.Exec(ctx, updateSellButtonRight, arg.TelegramID, arg.SellButtonRight, arg.UpdatedAt)
	return err
}

const updateSellSlippage = `-- name: UpdateSellSlippage :exec
UPDATE settings SET sell_slippage = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateSellSlippageParams struct {
	TelegramID   int64
	SellSlippage int16
	UpdatedAt    pgtype.Timestamp
}

func (q *Queries) UpdateSellSlippage(ctx context.Context, arg UpdateSellSlippageParams) error {
	_, err := q.db.Exec(ctx, updateSellSlippage, arg.TelegramID, arg.SellSlippage, arg.UpdatedAt)
	return err
}
