// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (trader, wallet_address, from_token, to_token, from_amount, to_amount, tx_hash, trade_unix_timestamp, webhook_event_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertTransactionParams struct {
	Trader             pgtype.Int8
	WalletAddress      string
	FromToken          string
	ToToken            string
	FromAmount         pgtype.Numeric
	ToAmount           pgtype.Numeric
	TxHash             string
	TradeUnixTimestamp pgtype.Timestamp
	WebhookEventID     pgtype.Text
	CreatedAt          pgtype.Timestamp
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.Trader,
		arg.WalletAddress,
		arg.FromToken,
		arg.ToToken,
		arg.FromAmount,
		arg.ToAmount,
		arg.TxHash,
		arg.TradeUnixTimestamp,
		arg.WebhookEventID,
		arg.CreatedAt,
	)
	return err
}
