// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(telegram_id, wallet_address, referrer_id, referral_code, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	TelegramID    int64
	WalletAddress string
	ReferrerID    sql.NullInt64
	ReferralCode  string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.TelegramID,
		arg.WalletAddress,
		arg.ReferrerID,
		arg.ReferralCode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getReferralCode = `-- name: GetReferralCode :one
SELECT referral_code FROM users
WHERE telegram_id = $1
`

func (q *Queries) GetReferralCode(ctx context.Context, telegramID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getReferralCode, telegramID)
	var referral_code string
	err := row.Scan(&referral_code)
	return referral_code, err
}

const getReferralCount = `-- name: GetReferralCount :one
SELECT COUNT(referrer_id) FROM users
WHERE referrer_id = $1
`

func (q *Queries) GetReferralCount(ctx context.Context, referrerID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReferralCount, referrerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT telegram_id, wallet_address, referrer_id, referral_code, created_at, updated_at FROM users
WHERE telegram_id = $1
`

func (q *Queries) GetUser(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, telegramID)
	var i User
	err := row.Scan(
		&i.TelegramID,
		&i.WalletAddress,
		&i.ReferrerID,
		&i.ReferralCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByRefCode = `-- name: GetUserByRefCode :one
SELECT telegram_id FROM users
WHERE referral_code = $1
`

func (q *Queries) GetUserByRefCode(ctx context.Context, referralCode string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserByRefCode, referralCode)
	var telegram_id int64
	err := row.Scan(&telegram_id)
	return telegram_id, err
}

const getWalletAddress = `-- name: GetWalletAddress :one
SELECT wallet_address FROM users
WHERE telegram_id = $1
`

func (q *Queries) GetWalletAddress(ctx context.Context, telegramID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getWalletAddress, telegramID)
	var wallet_address string
	err := row.Scan(&wallet_address)
	return wallet_address, err
}

const isExistingRefCode = `-- name: IsExistingRefCode :one
SELECT EXISTS (SELECT 1 FROM users WHERE users.referral_code = $1 LIMIT 1)
`

func (q *Queries) IsExistingRefCode(ctx context.Context, referralCode string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isExistingRefCode, referralCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isExistingUser = `-- name: IsExistingUser :one
SELECT EXISTS (SELECT 1 FROM users WHERE users.telegram_id = $1 LIMIT 1)
`

func (q *Queries) IsExistingUser(ctx context.Context, telegramID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, isExistingUser, telegramID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateWallet = `-- name: UpdateWallet :exec
UPDATE users SET wallet_address = $2, updated_at = $3
WHERE telegram_id = $1
`

type UpdateWalletParams struct {
	TelegramID    int64
	WalletAddress string
	UpdatedAt     time.Time
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) error {
	_, err := q.db.ExecContext(ctx, updateWallet, arg.TelegramID, arg.WalletAddress, arg.UpdatedAt)
	return err
}
